### ISSUE TITLE
`fal flow run` does not select scripts with certain selector

### ISSUE THREAD

**Issue by Antobiotics** [fal-ai/fal#281]
When using `fal flow run` with a selector, for example `fal flow run -m "+final_model"`
FAL does not select the scripe parent nodes that are directly after a DBT model node predecessor.

It seems to appear: https://github.com/fal-ai/fal/blob/0fe92da47472733eb7ee793b02b16b1f05f39371/src/fal/cli/selectors.py#L77

**Comment by chamini2** [comment]
In the above commit I added an example of this issue happening. Run

```
fal flow run --experimental-flow
```
to get the correct behavior:
```
fal flow run --profiles-dir .. --experimental-flow

17:18:20  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
Executing command: dbt --log-format json run --project-dir /Users/matteo/Projects/fal/fal/integration_tests/projects/006_test --profiles-dir .. --select some_model features_input
Running with dbt=1.1.0
Found 3 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
Concurrency: 4 threads (target='dev')
1 of 2 START view model dbt_fal.features_input ................................. [RUN]
2 of 2 START table model dbt_fal.some_model .................................... [RUN]
2 of 2 OK created table model dbt_fal.some_model ............................... [SELECT 1 in 0.22s]
1 of 2 OK created view model dbt_fal.features_input ............................ [CREATE VIEW in 0.22s]
Finished running 1 table model, 1 view model in 0.49s.
Completed successfully
Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2

13:18:32 | Starting fal run for following models and scripts:
features_input: /Users/matteo/Projects/fal/fal/integration_tests/projects/006_test/scripts/fal/predict.py

Concurrency: 4 threads

Executing command: dbt --log-format json run --project-dir /Users/matteo/Projects/fal/fal/integration_tests/projects/006_test --profiles-dir .. --select last_predictions all_predictions
Running with dbt=1.1.0
Found 3 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
The selection criterion 'all_predictions' does not match any nodes
Concurrency: 4 threads (target='dev')
1 of 1 START view model dbt_fal.last_predictions ............................... [RUN]
1 of 1 OK created view model dbt_fal.last_predictions .......................... [CREATE VIEW in 0.13s]
Finished running 1 view model in 0.29s.
Completed successfully
Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

vs

```
fal flow run --experimental-flow --select +last_predictions
```
to show the error:
```
fal flow run --profiles-dir .. --experimental-flow --select +last_predictions

18:19:18  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
Executing command: dbt --log-format json run --project-dir /Users/matteo/Projects/fal/fal/integration_tests/projects/006_test --profiles-dir .. --select features_input
Running with dbt=1.1.0
Found 3 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
Concurrency: 4 threads (target='dev')
1 of 1 START view model dbt_fal.features_input ................................. [RUN]
1 of 1 OK created view model dbt_fal.features_input ............................ [CREATE VIEW in 0.12s]
Finished running 1 view model in 0.44s.
Completed successfully
Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

Executing command: dbt --log-format json run --project-dir /Users/matteo/Projects/fal/fal/integration_tests/projects/006_test --profiles-dir .. --select last_predictions all_predictions
Running with dbt=1.1.0
Found 3 models, 0 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
The selection criterion 'all_predictions' does not match any nodes
Concurrency: 4 threads (target='dev')
1 of 1 START view model dbt_fal.last_predictions ............................... [RUN]
1 of 1 OK created view model dbt_fal.last_predictions .......................... [CREATE VIEW in 0.09s]
Finished running 1 view model in 0.25s.
Completed successfully
Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

**Comment by chamini2** [comment]
Hey @Antobiotics , as it happens, this is actually expected behavior for the current implementation.

We currently build a graph where any fal after-script is considered a node itself. And the dbt graph is kept as it was, just with some new nodes _downstream_ of the existing nodes.

In this example it would look like this:
![image](https://user-images.githubusercontent.com/2745502/166558968-7f746ce2-9610-4a58-9c92-a7afbfdccc15.png)

So, calling a selection like `--select +last_predictions` actually runs the [correct nodes based on dbt's selection documentation](https://docs.getdbt.com/reference/node-selection/graph-operators#the-plus-operator):
![image](https://user-images.githubusercontent.com/2745502/166559315-ad4b7b55-2266-4667-b5f6-d492d73aa6f9.png)

So, in order to get this working for now you could do `--select +last_predictions scripts/fal/predict.py` which is saying (all the parents and this one specific script) or change the criteria to something like `--select +features_input+ --except other_model_that_you_do_not_want_to_run+`

*****

I understand that what we would actually like to _represent_ in the graph looks more like
![image](https://user-images.githubusercontent.com/2745502/166561013-71380804-89db-4023-bbe3-f0cccefe6fa6.png)

And this enables you to do `--select +last_predictions` and get the expected results. And we are actually working in a way to achieve this with Python models (full models, not SQL models with Python attached to it).
I am currently working on this proposal and hopefully will make it into the product soon.

I will update this issue whenever we have this.

Thanks for reaching out!

**Comment by Antobiotics** [comment]
Hi! Thank you for coming back to me with such clear explanation and thank you for the selector suggestions. I will use that meanwhile you are developing those new features.

The idea of having python models would be amazing actually, that would really help making the flows clear to the user and keep the graph building process relatively simple!

I really like the ideas behind FAL, so it was a pleasure to explore a little bit the codebase.

**Comment by smithj51** [comment]
hi, I'm having a similar issue with selectors
I run the following:
`fal flow run --select test1 pre_script.py post_script.py`
which works great! the "before" python script runs, the model runs, and the "after" python script runs.
it should end there, but it starts doing "fal run" on all the other models. why is that? and how do I avoid that?

**Comment by chamini2** [comment]
Hello @smithj51 and @Antobiotics, we have recently introduced `post-hooks` scripts, which always run alongside their models. This is probably what you would like to use for the use case you are describing.

So

```yaml
version: 2

models:
  - name: features_input
    meta:
      fal:
        scripts:
          - scripts/fal/predict.py
```

would become

```yaml
version: 2

models:
  - name: features_input
    meta:
      fal:
        post-hooks:
          - scripts/fal/predict.py
```

*****

And it would run the `predict.py` after `features_input` *always*, even if it fails (with a status representing if it passed or failed).

```py
# predict.py

if context.current_model.status != "success":
  exit(0) # or raise, or whatever makes sense
```
