### ISSUE TITLE
How do I import own module?

### ISSUE THREAD

**Issue by ProdigyMaster** [fal-ai/fal#310]
**Describe the bug**
Hey Guys 👋, I have a problem with importing my own module into fal:

![image](https://user-images.githubusercontent.com/528501/168607711-c45e2ed2-aeb2-44d6-ae0b-3ff1a36b7b28.png)

I want  fal to run only the main.py script, and other modules are imported inside the main:
![image](https://user-images.githubusercontent.com/528501/168608005-fc7856f8-0a00-436b-a56d-1841362aa65f.png)

The problem is when I run fal I have got an error: 
![image](https://user-images.githubusercontent.com/528501/168608170-bfeb4b5b-3b6c-4c00-bbe6-510b5d5a071e.png)

Scripts work perfectly when run without fal

**Desktop (please complete the following information):**
 - OS: Windows

Thanks a lot! 😀

**Comment by chamini2** [comment]
Hello, @ProdigyMaster, one easy way to do this is shown in this integration test: https://github.com/fal-ai/fal/tree/main/integration_tests/projects/006_script_paths/scripts

We have the script 

https://github.com/fal-ai/fal/blob/97bac5ab8757d282f37985c50450df0ed86e8b3f/integration_tests/projects/006_script_paths/scripts/after.py#L1-L3

and the directory structure looks like: 

```
scripts/
├── after.py
├── before.py
└── utils
    ├── my_utils.py
    └── process
        └── process_df.py
```

*****

Does this work for you?

**Comment by ProdigyMaster** [comment]
![image](https://user-images.githubusercontent.com/528501/168747353-f2045e30-a53f-4413-b005-278a74085861.png)
![image](https://user-images.githubusercontent.com/528501/168747413-4cb0aebe-4dc6-413d-a6f5-d208d8c1a4b4.png)
![image](https://user-images.githubusercontent.com/528501/168747497-a1ab601f-538e-49e6-9c68-c55928404567.png)

@chamini2 Same Error. Sorry I probably don't get it 😥

**Comment by ProdigyMaster** [comment]
Ok, the only way it works is to add absolute path to sys.path, and run it before main.py
![image](https://user-images.githubusercontent.com/528501/168765456-cd06e5b2-4804-47d5-abba-0dc4af525019.png)
![image](https://user-images.githubusercontent.com/528501/168765588-7a03a3e0-b94a-461f-ba87-730b43306bcc.png)

If you have any other smarter way, I would appreciate 😀

**Comment by ProdigyMaster** [comment]
But the question is why fal doesn't add other files in the python folder to the path automatically? 🤔

**Comment by chamini2** [comment]
Hello, @ProdigyMaster. Sorry that I am getting back to you so late. 

fal does include a base directory from which to import your other scripts, it is by default the project dir. Which is the directory in which `dbt_project.yml` is. 

In the case described here:

> **Describe the bug** Hey Guys 👋, I have a problem with importing my own module into fal:
> 
> ![image](https://user-images.githubusercontent.com/528501/168607711-c45e2ed2-aeb2-44d6-ae0b-3ff1a36b7b28.png)
> 
> I want fal to run only the main.py script, and other modules are imported inside the main: ![image](https://user-images.githubusercontent.com/528501/168608005-fc7856f8-0a00-436b-a56d-1841362aa65f.png)

I think doing `import python.big_query_get_attributes as big_query` would do the trick. That is, adding a `python.` at the beginning of the `import` path because it searches from the project directory.

In case you want to change the scripts path, you can add the following var to your `dbt_project.yml`

```yaml
vars:
  fal-scripts-path: "python"
```

So it imports from the path you expected.

Please let me know if this helps or not, I will be adding documentation about this in #317 (you can see some examples being added there).

**Comment by ProdigyMaster** [comment]
@chamini2 It works! 🎉 Thank you very much 😀
